fifty_quotes = [
    ("Don’t let yesterday take up too much of today.", "Will Rogers"),
    ("If you’re going through hell, keep going.", "Winston Churchill"),
    ("Every man dies. Not every man lives.", "William Wallace"),
    ("Life shrinks or expands in proportion to one’s courage.", "Anais Nin"),
    ("Nothing is impossible. The word itself says “I’m possible!", "Audrey Hepburn"),
    ("We need much less than we think we need.", "Maya Angelou"),
    ("If things go wrong, don’t go with them.", "Roger Babson"),
    ("Everything has beauty, but not everyone sees it.", "Confucius"),
    ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
    ("There is no way to happiness Happiness is the way.", "Thich Nhat Hanh"),
    ("Whatever you are, be a good one.", "Abraham Lincoln"),
    ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("The only real mistake is the one from which we learn nothing.", "Henry Ford"),
    ("Positive anything is better than negative nothing.", "Elbert Hubbard"),
    ("Limit your ‘always’ and your ‘nevers’.", "Amy Poehler"),
    ("Creativity is intelligence having fun.", "Albert Einstein"),
    ("If you tell the truth you don’t have to remember anything.", "Mark Twain"),
    ("Be so good they can’t ignore you.", "Steve Martin"),
    ("There is no substitute for hard work.", "Thomas Edison"),
    ("Try to be a rainbow in someone else’s cloud.", "Maya Angelou"),
    ("You do not find the happy life. You make it.", "Camilla Eyring Kimball"),
    ("Sometimes you will never know the value of a moment, until it becomes a memory.", "Dr. Seuss"),
    ("Happiness depends upon ourselves.", "Aristotle"),
    ("If you look at what you have in life, you’ll always have more.", "Oprah Winfrey"),
    ("Yesterday’s the past, tomorrow’s the future, but today is a gift. That’s why it’s called the present.",
     "Bil Keane"),
    ("Time moves in one direction, memory in another.", "William Gibson"),
    ("Lose an hour in the morning, and you will spend all day looking for it.", "Richard Whately"),
    ("To improve is to change; to be perfect is to change often.", "Winston Churchill"),
    ("Every accomplishment starts with the decision to try.", "Brian Littrell"),
    ("Every moment is a fresh beginning.", "T.S Eliot"),
    ("Never regret anything that made you smile.", "Mark Twain"),
    ("Dream as if you’ll live forever, live as if you’ll die today.", "James Dean"),
    ("All limitations are self-imposed.", "Oliver Wendell Holmes"),
    ("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    ("Problems are not stop signs, they are guidelines.", "Robert H. Schiuller"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.",
     "Winston Churchill"),
    ("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
    ("No matter what you’re going through, there’s a light at the end of the tunnel.", "Demi Lovato"),
    ("What we think, we become.", "Buddha"),
    ("It is never too late to be what you might have been.", "George Eliot"),
    ("Happiness often sneaks in through a door you didn’t know you left open.", "John Barrymore"),
    ("Happiness is not by chance, but by choice.", "Jim Rohn"),
    ("Life changes very quickly, in a very positive way, if you let it.", "Lindsey Vonn"),
    ("Keep your face to the sunshine and you cannot see a shadow.", "Helen Keller"),
    ("Be the change that you wish to see in the world.", "Mahatma Gandhi"),
    ("If I cannot do great things, I can do small things in a great way.", "Martin Luther King Jr."),
    ("The bad news is time flies. The good news is you’re the pilot.", "Michael Altshuler"),
    ("Don’t wait. The time will never be just right", "Napoleon Hillf"),
    ("No matter what people tell you, words and ideas can change the world.", "Robin Williams")
]